name: Trigger auto deployment for capp-sample104

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/capp-sample104-AutoDeployTrigger-28cb8513-d31f-48ad-995c-16b3cea550ca.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CAPPSAMPLE104_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CAPPSAMPLE104_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CAPPSAMPLE104_AZURE_SUBSCRIPTION_ID }}

      - name: Clone azure-cli-extensions repo
        uses: actions/checkout@v3
        with:
          repository: snehapar9/azure-cli-extensions
          path: azure-cli-extensions
      - name: Install latest azure-cli-extensions wheel
        run: az extension add --source '${{ github.workspace }}/azure-cli-extensions/containerapp-0.3.43-py2.py3-none-any.whl"' --yes

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@d7d06e687ee7ed845cf7aee49a81b30cc6ec1960
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.CAPPSAMPLE104_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CAPPSAMPLE104_REGISTRY_PASSWORD }}
          containerAppName: capp-sample104
          resourceGroup: ca-snehapar-group
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          


