name: Trigger auto deployment for capp-snehapar-oidc-test-westus2

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/capp-snehapar-oidc-test-westus2-AutoDeployTrigger-57225a14-0e78-4b72-aac6-3585d6e93bcc.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CAPPSNEHAPAROIDCTESTWESTUS2_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CAPPSNEHAPAROIDCTESTWESTUS2_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CAPPSNEHAPAROIDCTESTWESTUS2_AZURE_SUBSCRIPTION_ID }}
      - name: Clone azure-cli-extensions repo
        uses: actions/checkout@v3
        with:
          repository: snehapar9/test
          path: azure-cli-extensions
          
      - name: Install latest azure-cli-extensions wheel
        run: az extension add --source '${{ github.workspace }}/azure-cli-extensions/containerapp-0.3.43-py2.py3-none-any.whl' --yes

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@145abc77db9d08e6fd0f6b750ebbbbe182b44701
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.CAPPSNEHAPAROIDCTESTWESTUS2_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CAPPSNEHAPAROIDCTESTWESTUS2_REGISTRY_PASSWORD }}
          containerAppName: capp-snehapar-oidc-test-westus2
          resourceGroup: ca-snehapar-oidc-westus-rg
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          


