name: Trigger auto deployment for capp-test-oidc-asdfjkl99

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/capp-test-oidc-asdfjkl99-AutoDeployTrigger-de0573d4-d270-4681-b35a-945763ca4b4b.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CAPPTESTOIDCASDFJKL99_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CAPPTESTOIDCASDFJKL99_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CAPPTESTOIDCASDFJKL99_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.CAPPTESTOIDCASDFJKL99_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CAPPTESTOIDCASDFJKL99_REGISTRY_PASSWORD }}
          containerAppName: capp-test-oidc-asdfjkl99
          resourceGroup: ca-snehapar-oidc-test-rg
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          


