name: Trigger auto deployment for capp-sne-northcentralusstage

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/capp-sne-northcentralusstage-AutoDeployTrigger-755f7cca-be53-43f8-b0e1-9b0063279233.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CAPPSNENORTHCENTRALUSSTAGE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CAPPSNENORTHCENTRALUSSTAGE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CAPPSNENORTHCENTRALUSSTAGE_AZURE_SUBSCRIPTION_ID }}

      - name: Clone azure-cli-extensions repo
        uses: actions/checkout@v3
        with:
          repository: snehapar9/test
          path: azure-cli-extensions
          
      - name: Install latest azure-cli-extensions wheel
        run: az extension add --source '${{ github.workspace }}/azure-cli-extensions/containerapp-0.3.43-py2.py3-none-any.whl' --yes

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@545e142e7cd5c71138c372adeaaa6661bb60d291
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.CAPPSNENORTHCENTRALUSSTAGE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CAPPSNENORTHCENTRALUSSTAGE_REGISTRY_PASSWORD }}
          containerAppName: capp-sne-northcentralusstage
          resourceGroup: ca-snehapar-test-rg
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          


