name: Trigger auto deployment for capp-test-sample103

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/capp-test-sample103-AutoDeployTrigger-94178f49-cfe3-4d04-9194-3cb3886d7208.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CAPPSNEHAPARSAMPLEREPO4_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.CAPPTESTSAMPLE103_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CAPPTESTSAMPLE103_REGISTRY_PASSWORD }}
          containerAppName: capp-test-sample103
          resourceGroup: ca-snehapar-group
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          


