name: Trigger auto deployment for capp-test-sample2

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/capp-test-sample2-AutoDeployTrigger-65319e6a-ffab-4ba0-b3f9-85b74db2a60c.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CAPPTESTSAMPLE2_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: snehaparacr.azurecr.io
          registryUsername: ${{ secrets.CAPPTESTSAMPLE2_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CAPPTESTSAMPLE2_REGISTRY_PASSWORD }}
          containerAppName: capp-test-sample2
          resourceGroup: ca-snehapar-group
          imageToBuild: snehaparacr.azurecr.io/capp-test-sample2:${{ github.sha }}
          

     

