name: Trigger auto deployment for capp-snehapar-sample-repo5

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/capp-snehapar-sample-repo5-AutoDeployTrigger-4692aa18-f070-4dda-8153-1930359af780.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CAPPSNEHAPARSAMPLEREPO5_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: snehaparacr.azurecr.io
          registryUsername: ${{ secrets.CAPPSNEHAPARSAMPLEREPO5_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CAPPSNEHAPARSAMPLEREPO5_REGISTRY_PASSWORD }}
          containerAppName: capp-snehapar-sample-repo5
          resourceGroup: ca-snehapar-group
          imageToBuild: snehaparacr.azurecr.io/capp-snehapar-sample-repo5:${{ github.sha }}
          

     

