name: Trigger auto deployment for capp-snehapar-oidc-westus-copy

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/capp-snehapar-oidc-westus-copy-AutoDeployTrigger-8fc6462c-83c5-4efe-9d3a-7280d32072dc.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CAPPSNEHAPAROIDCWESTUSCOPY_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CAPPSNEHAPAROIDCWESTUSCOPY_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CAPPSNEHAPAROIDCWESTUSCOPY_AZURE_SUBSCRIPTION_ID }}

      - name: Clone azure-cli-extensions repo
        uses: actions/checkout@v3
        with:
          repository: snehapar9/test
          path: azure-cli-extensions
          
      - name: Install latest azure-cli-extensions wheel
        run: az extension add --source '${{ github.workspace }}/azure-cli-extensions/containerapp-0.3.43-py2.py3-none-any.whl' --yes

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@e95c19a124624e6797f68977e811b2eb4621a9a4
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.CAPPSNEHAPAROIDCWESTUSCOPY_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CAPPSNEHAPAROIDCWESTUSCOPY_REGISTRY_PASSWORD }}
          containerAppName: capp-snehapar-oidc-westus-copy
          resourceGroup: ca-snehapar-rg-westus
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          


