name: Trigger auto deployment for test-sample999

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/test-sample999-AutoDeployTrigger-7e42682d-0d95-4417-8c14-b861a9663453.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.TESTSAMPLE999_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TESTSAMPLE999_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TESTSAMPLE999_AZURE_SUBSCRIPTION_ID }}

      - name: Clone azure-cli-extensions repo
        uses: actions/checkout@v3
        with:
          repository: snehapar9/test
          path: azure-cli-extensions
          
      - name: Install latest azure-cli-extensions wheel
        run: az extension add --source '${{ github.workspace }}/azure-cli-extensions/containerapp-0.3.43-py2.py3-none-any.whl' --yes

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@d7e56184f9212e83bb0581bf65051802141fa7f8
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.TESTSAMPLE999_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TESTSAMPLE999_REGISTRY_PASSWORD }}
          containerAppName: test-sample999
          resourceGroup: snehapar_rg_4570
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          


